import type { MaterialRecord } from "@/lib/types";

export const MATERIALS: MaterialRecord[] = [
  {
    name: "RCC",
    cost: 5,
    strength: 5,
    durability: 5,
    ease: 2,
    use: "load_bearing",
  },
  {
    name: "Red Brick",
    cost: 3.2,
    strength: 4.2,
    durability: 3.8,
    ease: 3,
    use: "load_bearing",
  },
  {
    name: "Fly Ash Brick",
    cost: 2.4,
    strength: 3.7,
    durability: 4.1,
    ease: 3.2,
    use: "general",
  },
  {
    name: "AAC Blocks",
    cost: 2,
    strength: 2.2,
    durability: 3.3,
    ease: 4.4,
    use: "partition",
  },
  {
    name: "Hollow Concrete Block",
    cost: 2.6,
    strength: 2.8,
    durability: 3,
    ease: 3.8,
    use: "partition",
  },
  {
    name: "Steel Frame",
    cost: 5,
    strength: 5,
    durability: 4.8,
    ease: 2.1,
    use: "long_span",
  },
  {
    name: "Precast Concrete Panel",
    cost: 4.1,
    strength: 4.2,
    durability: 4.7,
    ease: 3,
    use: "semi_structural",
  },
  {
    name: "Confined Masonry",
    cost: 3.4,
    strength: 4.3,
    durability: 4.2,
    ease: 2.9,
    use: "load_bearing",
  },
  {
    name: "Autoclaved Calcium Silicate Block",
    cost: 2.7,
    strength: 3.1,
    durability: 3.8,
    ease: 4.2,
    use: "partition",
  },
  {
    name: "Structural Steel + Deck Slab",
    cost: 4.8,
    strength: 4.9,
    durability: 4.5,
    ease: 2.5,
    use: "long_span",
  },
  {
    name: "Prestressed Concrete",
    cost: 4.9,
    strength: 5,
    durability: 4.9,
    ease: 2.2,
    use: "long_span",
  },
  {
    name: "Light Gauge Steel Stud",
    cost: 2.8,
    strength: 2.9,
    durability: 3.6,
    ease: 4.3,
    use: "partition",
  },
  {
    name: "Engineered Timber CLT Panel",
    cost: 4.3,
    strength: 4.1,
    durability: 3.9,
    ease: 3.4,
    use: "semi_structural",
  },
  {
    name: "Solid Concrete Block",
    cost: 3.5,
    strength: 4.4,
    durability: 4.3,
    ease: 2.8,
    use: "load_bearing",
  },
  {
    name: "Porotherm Hollow Clay Block",
    cost: 3.1,
    strength: 3.6,
    durability: 4,
    ease: 3.7,
    use: "partition",
  },
  {
    name: "GFRG Panel",
    cost: 3.9,
    strength: 4.1,
    durability: 4.2,
    ease: 3.6,
    use: "semi_structural",
  },
  {
    name: "RC Shear Wall System",
    cost: 4.7,
    strength: 4.9,
    durability: 4.8,
    ease: 2.3,
    use: "load_bearing",
  },
  {
    name: "Steel Tube Column",
    cost: 4.6,
    strength: 4.8,
    durability: 4.6,
    ease: 2.6,
    use: "long_span",
  },
  {
    name: "Composite Steel-Concrete Column",
    cost: 4.8,
    strength: 5,
    durability: 4.7,
    ease: 2.4,
    use: "long_span",
  },
  {
    name: "Brick Infill in RC Frame",
    cost: 2.9,
    strength: 3.2,
    durability: 3.7,
    ease: 3.8,
    use: "general",
  },
  {
    name: "Cellular Lightweight Concrete Panel",
    cost: 2.6,
    strength: 2.9,
    durability: 3.5,
    ease: 4.1,
    use: "partition",
  },
  {
    name: "M20 Cast-in-Situ Concrete",
    cost: 4.4,
    strength: 4.6,
    durability: 4.4,
    ease: 2.6,
    use: "load_bearing",
  },
  {
    name: "M25 Reinforced Concrete",
    cost: 4.7,
    strength: 4.9,
    durability: 4.7,
    ease: 2.4,
    use: "load_bearing",
  },
  {
    name: "High-Strength Rebar Concrete",
    cost: 4.9,
    strength: 5,
    durability: 4.9,
    ease: 2.2,
    use: "long_span",
  },
  {
    name: "Aluminium Formwork RC Wall",
    cost: 4.2,
    strength: 4.4,
    durability: 4.5,
    ease: 3.3,
    use: "semi_structural",
  },
  {
    name: "Gypsum Board on Metal Stud",
    cost: 1.9,
    strength: 1.9,
    durability: 2.8,
    ease: 4.8,
    use: "partition",
  },
  {
    name: "CSEB (Stabilized Earth Block)",
    cost: 1.8,
    strength: 2.6,
    durability: 3.2,
    ease: 3.9,
    use: "general",
  },
  {
    name: "Insulated Sandwich Panel",
    cost: 3.7,
    strength: 3.5,
    durability: 4.1,
    ease: 4.2,
    use: "semi_structural",
  },
  {
    name: "Aluminium Window System",
    cost: 3.4,
    strength: 3.1,
    durability: 4.3,
    ease: 4.4,
    use: "general",
  },
  {
    name: "uPVC Window System",
    cost: 2.5,
    strength: 2.4,
    durability: 3.8,
    ease: 4.6,
    use: "general",
  },
];
